apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: demo-app         
      version: blue
  template:
    metadata:
      name: demo-app-pod
      labels:
        app: demo-app
        version: blue
    spec:
      containers:
      - name: demo-app-container
        image: 6752/repo-for-devops:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service 
metadata:
  name: demo-app-svc
  labels:
    app: demo-app
spec:
  selector:
    app: demo-app
    version: v1
  type: NodePort
  ports:
  - nodePort: 31113
    port: 80
    targetPort: 80    
