apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: mentorat
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mentorat
  template:
    metadata:
      labels:
        app: mentorat
    spec:
      containers:
      - name: mentorat
        image: zmihai/pregatit-demo-app-python
        imagePullPolicy: Never
        ports:
        - containerPort: 5000      

---
apiVersion: v1
kind: Service
metadata:
  name: app-deployment
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: mentorat
  type: NodePort
